# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
    compile:
        name: Cross compile using landgenoot/kindle-cross-compile-toolchain
        runs-on: ubuntu-latest
        steps:
          - name: Check out the repo
            uses: actions/checkout@v2

          - name: Run the build process with Docker
            uses: addnab/docker-run-action@v3
            with:
                image: landgenoot/kindle-cross-compile-toolchain:latest
                options: -v ${{ github.workspace }}:/workdir
                run: |
                    cd /workdir
                    CGO_LDFLAGS="-Wl,-rpath=/mnt/us/linkss/lib" CC="arm-linux-gnueabi-gcc -fopenmp" PKG_CONFIG_LIBDIR=/usr/lib/arm-linux-gnueabi/pkgconfig GOOS=linux GOARCH=arm CGO_ENABLED=1 go build -o photoframe -buildvcs=false
                    ls

          - name: Upload release
            uses: actions/upload-artifact@v3
            with:
              name: kindle-synology-photos-photoframe-${{ github.sha }}
              path: |
                photoframe     
                assets/*/lib